language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: deploy
      script:
        - node .travis/setupGithubPages.js
        - .travis/push.sh
stages:
  - name: deploy
    if: type = push AND branch = master